### ISSUE TITLE
about cache question

### ISSUE THREAD

**Issue by XiongMM** [ExampleDriven/spring-cloud-hystrix-example#1]
Hi,I run your program,but,I have a question about request cache.
when I run http://localhost:8080/customer-cache/2?name=Peter  I got the data {"id":2,"firstName":"Peter","lastName":"Peter"}
when I run http://localhost:8080/customer-cache/2?name=Peter2 I got the data 
{"id":2,"firstName":"Peter2","lastName":"Peter2"}
The results of the two runs are different?
I think,the first result should be cache? the second result should be {"id":2,"firstName":"Peter","lastName":"Peter"} ?

can you tell me why?How should reflect the cache?

Thanks!

**Comment by szantopeter** [comment]
You are right the cache is not working. I think it used to work, but it was a year ago... In general I lost interest in the caching part as there are better ways to do it. If you find the reason why it is not working then a pull request is welcome!

**Comment by XiongMM** [comment]
OK, I will put the reasons here If I find it.Thank you for your answer.

**Comment by szantopeter** [comment]
It was actually a cache context issue. See 
https://github.com/ExampleDriven/spring-cloud-hystrix-example/blob/master/hystrix-example/src/main/java/org/exampledriven/hystrixeample/config/HystrixContextInterceptor.java
